# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: local
    hooks:
        - id: pylint
          name: Pylint
          entry: /Users/vibhavaribellutagi/.pyenv/shims/pylint
          language: system
          types: [python]
          args:
            [
                "--rcfile=./.pylintrc",
            ]
